<!DOCTYPE html>
<html lang="ru" class="h-100">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Анализатор страниц</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </head>
  <body>
  <main>
      <div class="container mt-3">
        <h1>Сайты</h1>
        <table class="table table-hover table-bordered" data-test="urls">
          <tbody>
            <tr>
              <th>ID</th>
              <th>Имя</th>
              <th>Последняя проверка</th>
              <th>Код ответа</th>
            </tr>
            <?php foreach ($data as $url) : ?>
              <tr>
                <td><?= $url['id'] ?></td>
                <td>
                  <a href="<?= $router->urlFor('urls.show', ['id' => $url['id']]) ?>">
                    <?= $url['name'] ?>
                  </a>
                </td>
                <td><?= $url['last_check_created_at'] ?></td>
                <td><?= $url['status_code'] ?></td>
              </tr>
            <?php endforeach ?>
          </tbody>
        </table>
      </div>
    </main>
  </body>
</html>