<!DOCTYPE html>
<html lang="ru" class="h-100">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Анализатор страниц</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </head>
  <body>
  <main class="flex-grow-1">
      <div class="container my-3">
        <div class="p-5 mx-auto col-lg-8 bg-body-tertiary border rounded-3">
          <h1 class="display-3">Анализатор страниц</h1>
          <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
          <!-- <form class="row mb-3" action="<?= $router->urlFor('urls.store') ?>" method="post" required> -->
          <form class="row mb-3" action="/" method="get" required>
            <div class="col-8">
              <input
                type="text"
                name="url[name]"
                value="<?= htmlspecialchars($url ?? '') ?>"
                class="form-control form-control-lg
                    <?php if (isset($errors['url_name'])) : ?>
                      is-invalid
                    <?php endif ?>"
                aria-describedby="validationFeedback"
                placeholder="https://www.example.com">
              <?php if (isset($errors['url_name'])) : ?>
                <div id="validationFeedback" class="invalid-feedback"><?= $errors['url_name'][0] ?></div>
              <?php endif ?>
            </div>
            <div class="col-4">
              <input type="submit" class="btn btn-primary btn-lg px-5 text-uppercase" value="Проверить">
            </div>
          </form>
        </div>
      </div>
    </main>
  </body>
</html>
