<!DOCTYPE html>
<html lang="ru" class="h-100">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Анализатор страниц</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-dark ps-1" data-bs-theme="dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="<?= $router->urlFor('home') ?>">Анализатор страниц</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link <?= $routeName === 'home' ? 'active' : '' ?>"
                  href="<?= $router->urlFor('home') ?>">
                  Главная
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link <?= $routeName === 'urls.index' ? 'active' : '' ?>"
                  href="<?= $router->urlFor('urls.index') ?>">
                  Сайты
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div>
      <?php if (isset($flash['success'])) : ?>
            <?php foreach ($flash['success'] as $message) : ?>
              <div class="alert alert-success" role="alert"><?= $message ?></div>
            <?php endforeach ?>
      <?php elseif (isset($flash['warning'])) : ?>
            <?php foreach ($flash['warning'] as $message) : ?>
              <div class="alert alert-warning" role="alert"><?= $message ?></div>
            <?php endforeach ?>
      <?php elseif (isset($flash['error'])) : ?>
            <?php foreach ($flash['error'] as $message) : ?>
              <div class="alert alert-danger" role="alert"><?= $message ?></div>
            <?php endforeach ?>
      <?php endif ?>
    </div>
    <?= $content ?>
  </body>
</html>
    